Send slack notification if health check fails, and on successful run

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,14 +6,17 @@ on:
       - completed
     branches:
       - master
+env:
+  SSH_USER: ${{ secrets.SSH_USER }}
+  SSH_HOST: ${{ secrets.SSH_HOST }}
+  APP_NAME: url_shortener
+  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
+  REGISTRY_USER: ${{ github.actor }}
 jobs:
   build_and_upload:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     env:
-      APP_NAME: url_shortener
-      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
-      REGISTRY_USER: ${{ github.actor }}
       DOCKER_BUILD_PUSH_PASSWORD: ${{ secrets.DOCKER_BUILD_DEPLOY_TOKEN }}
     steps:
       - uses: actions/checkout@v3
@@ -30,30 +33,35 @@ jobs:
         run: |
           echo "${{ toJSON(steps.push_image.outputs) }}"
   health_check:
+    runs-on: ubuntu-latest
     needs: [build_and_upload]
-    runs:-on: ubuntu-latest
-    env:
-      SSH_HOST: ${{ secrets.SSH_HOST }}
     steps:
       - name: Check whether URL shortener is up
         id: health_check
         run: |
           curl $SSH_HOST/healthz
+  notify_unsuccessful_health_check:
+    runs-on: ubuntu-latest
+    needs: [health_check]
+    if: ${{ failure() }}
+    steps:
+      - name: Send slack notification
+        env:
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+        run: |
+          now=$(date +%Y-%m-%dT%H:%M:%S)
+          payload=$(echo "{\"text\":\"URL shortener backend: Health check for $SSH_HOST/healthz failed at <DATE>\"}" | sed "s~<DATE>~$now~")
+          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
+          exit 1
   deploy:
     runs-on: ubuntu-latest
     needs: [health_check]
-    env:
-      APP_NAME: url_shortener
-      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
-      REGISTRY_USER: ${{ github.actor }}
-      DOCKER_PULL_PASSWORD: ${{ secrets.DOCKER_PULL_TOKEN }}
-      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-      SSH_USER: ${{ secrets.SSH_USER }}
-      SSH_HOST: ${{ secrets.SSH_HOST }}
     steps:
       - uses: actions/checkout@v3        
       - name: Configure SSH
         id: ssh
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         run: |
           mkdir -p ~/.ssh/
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/url_shortener_rsa
@@ -78,6 +86,7 @@ jobs:
           REDIS_URL: ${{ secrets.REDIS_URL }}
           ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
           BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
+          DOCKER_PULL_PASSWORD: ${{ secrets.DOCKER_PULL_TOKEN }}
         run: |
           ssh production << EOF
           echo "Logging into container registry"
@@ -98,5 +107,28 @@ jobs:
           sleep 5
           docker ps
           EOF
+  notify_unsuccessful:
+    runs-on: ubuntu-latest
+    needs: [deploy]
+    if: ${{ failure() }}
+    steps:
+      - name: Send slack notification unsuccessful run    
+        env:
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+        run: |
+          now=$(date +%Y-%m-%dT%H:%M:%S)
+          payload=$(echo "{\"text\":\"URL shortener backend: Deployment failed at <DATE>\"}" | sed "s~<DATE>~$now~")
+          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
+  notify_successful:
+    runs-on: ubuntu-latest
+    needs: [deploy]
+    steps:
+      - name: Send slack notification successful run
+        env:
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+        run: |
+          now=$(date +%Y-%m-%dT%H:%M:%S)
+          payload=$(echo "{\"text\":\"URL shortener backend: Deployment succeeded at <DATE>\"}" | sed "s~<DATE>~$now~")
+          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
 
       
